# Generated by Django 5.0.6 on 2024-06-11 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autoevaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estrategia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autoevaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elama.autoevaluacion')),
            ],
        ),
        migrations.CreateModel(
            name='Principio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='', max_length=200)),
                ('estrategia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elama.estrategia')),
            ],
        ),
        migrations.CreateModel(
            name='Descriptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('principio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elama.principio')),
            ],
        ),
        migrations.CreateModel(
            name='Volcado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valoracion', models.IntegerField(default=1)),
                ('autoevaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elama.autoevaluacion')),
                ('descriptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elama.descriptor')),
            ],
        ),
    ]
